// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWX_t6eZeTyvRJZDEiNqk6D5SQJiXHQg',
    appId: '1:743343930585:android:065828d410a994c81752c8',
    messagingSenderId: '743343930585',
    projectId: 'dictionary-4f91f',
    storageBucket: 'dictionary-4f91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjIzq7y9ruBB0zZdjTeuXc4TckNZTyh4',
    appId: '1:743343930585:ios:38ccb2b664a043021752c8',
    messagingSenderId: '743343930585',
    projectId: 'dictionary-4f91f',
    storageBucket: 'dictionary-4f91f.appspot.com',
    iosClientId: '743343930585-3m8kqb65i20136iknv09cddm821l9vej.apps.googleusercontent.com',
    iosBundleId: 'wolfcodea.com.dictionary',
  );
}
