name: dictionary
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.4
  connectivity_plus: ^4.0.1
  equatable: ^2.0.5
  http: ^0.13.5
  http_interceptor: ^1.0.2
  dartz: ^0.10.1
  material_design_icons_flutter: ^6.0.7096
  floor: ^1.3.0
  firebase_remote_config: ^4.2.1
  firebase_core: ^2.1.0
  flutter_tts: ^3.7.0
  another_flushbar: ^1.10.24

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  effective_dart: ^1.3.2
  floor_generator: ^1.3.0
  build_runner: ^2.4.6
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
